"""add missedmoment.quote (stage 4)

Revision ID: 24bcced33d9d
Revises: 540659cb5c68
Create Date: 2026-07-03 11:40:49.383319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bcced33d9d'
down_revision = '540659cb5c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missed_moments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missed_moments', schema=None) as batch_op:
        batch_op.drop_column('quote')

    # ### end Alembic commands ###
