"""add call.manager_channel (stage 3)

Revision ID: 540659cb5c68
Revises: 18f157672ac2
Create Date: 2026-07-03 09:00:48.059360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540659cb5c68'
down_revision = '18f157672ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_channel', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_column('manager_channel')

    # ### end Alembic commands ###
