"""add call.excluded

Revision ID: 57a69924c166
Revises: bb6b4fc868eb
Create Date: 2026-07-05 06:38:07.294669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a69924c166'
down_revision = 'bb6b4fc868eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_column('excluded')

    # ### end Alembic commands ###
