"""add deals

Revision ID: 74f73daefcb2
Revises: 57a69924c166
Create Date: 2026-07-05 11:13:39.021187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f73daefcb2'
down_revision = '57a69924c166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amo_lead_id', sa.BigInteger(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('pipeline_id', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('won_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_amo_lead_id'), ['amo_lead_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_deals_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_won_at'), ['won_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_won_at'))
        batch_op.drop_index(batch_op.f('ix_deals_manager_id'))
        batch_op.drop_index(batch_op.f('ix_deals_amo_lead_id'))

    op.drop_table('deals')
    # ### end Alembic commands ###
