"""add departments + user.department_id

Revision ID: 935a5b3eae91
Revises: 24bcced33d9d
Create Date: 2026-07-03 16:08:15.653238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935a5b3eae91'
down_revision = '24bcced33d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_users_department_id', 'departments', ['department_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_department_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_column('department_id')

    op.drop_table('departments')
    # ### end Alembic commands ###
