"""add call amo_entity link fields

Revision ID: bb6b4fc868eb
Revises: 4d28f370ac77
Create Date: 2026-07-05 05:47:31.767290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6b4fc868eb'
down_revision = '4d28f370ac77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amo_entity_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('amo_entity_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_column('amo_entity_id')
        batch_op.drop_column('amo_entity_type')

    # ### end Alembic commands ###
